### ISSUE TITLE
share功能的ip地址非局域网ip也非公网ip

### ISSUE THREAD

**Issue by aoliaoaoaojiao** [SonicCloudOrg/sonic-android-supply#1]
<img width="346" alt="d418fb103fed69e06d76aa07676cff5" src="https://user-images.githubusercontent.com/53102695/193454041-7c844244-554c-4f66-843b-8bc85e1e8078.png">

**Comment by ZhouYixun** [comment]
在 https://github.com/SonicCloudOrg/sonic-android-supply/commit/b48395e95bfeb85abe383f9a12e38fa3ca3aea50 调整为只展示port，因为ip比较多变而且用户自己能准确感知，于是改动为这样
