### ISSUE TITLE
单一的sas是否支持可视化界面

### ISSUE THREAD

**Issue by wyoung1** [SonicCloudOrg/sonic-android-supply#3]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

Hi，我希望可视化sas捕捉到的android设备的性能数据，完整的sonic云真机测试平台似乎支持这个功能，但是我在部署时遇到了一点麻烦，请问单独的sas工具是否支持可视化功能呢？谢谢！

### Deploy platform

windows10

### Minimal reproduce step

sas

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by wyoung1** [comment]
@aoliaoaoaojiao @ZhouYixun

**Comment by ZhouYixun** [comment]
不支持
